version: "2"
services:
  resale-global-portal:
    container_name: portal
    build:
      context: .
      dockerfile: Dockerfile
    image: trow.kube-public:31000/resale_global_portal
    stdin_open: true
    tty: true
    ports:
      - "80:80"